# A place to conveniently store all the types of tokens for universal reference
# Value types
NUMBER, STRING = 'NUMBER', 'STRING' 

# Structure symbols
LEFT_PAREN, RIGHT_PAREN, LEFT_BRACK, RIGHT_BRACK = 'LEFT_PAREN', 'RIGHT_PAREN', 'LEFT_BRACK', 'LEFT_BRACK'
LEFT_BRACE, RIGHT_BRACE = 'LEFT_BRACE', 'RIGHT_BRACE'
COMMA, SEMICOLON, EOL, EOF = 'COMMA', 'SEMICOLON', 'EOL', 'EOF'

# Math symbols
PLUS, MINUS, DIVIDE, MULTIPLY = 'PLUS', 'MINUS', 'DIVIDE', 'MULTIPLY'

# Logic symbols
AND, OR = 'AND', 'OR'
NOT, GREATER_THAN, LESS_THAN = 'NOT', 'GREATER_THAN', 'LESS_THAN'
NOT_EQUAL, GREATER_OR_EQUAL, LESS_OR_EQUAL = 'NOT_EQUAL', 'GREATER_OR_EQUAL', 'LESS_OR_EQUAL'
ASSIGN = 'ASSIGN'
EQUIVALENT = 'EQUIVALENT'

# Reserved words
POINT, SOLID, FORCE, UPDATE, POS = 'POINT', 'SOLID', 'FORCE', 'UPDATE', 'POS'
VAR, IDENTIFIER = 'VAR', 'IDENTIFIER'

# Ignore
IGNORE = 'IGNORE'

# Undefined (default)
UNDEFINED = 'UNDEFINED'